### ISSUE TITLE
OpenSubtitles.com Implementation

### ISSUE THREAD

**Issue by TwilightMercy** [Nitzantomer1998/UniversalHebrewSubtitles#4]
Hi,

I would like contribute (as much as I can) to your addon development.
Unfortunately, I don't know JS that much (python focused), So you won't see from me any actual PRs.

But as an Kodi developer, The following Israeli subtitles addon called "DarkSubs", can help you for implementation examples if you want.

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/0e8390dc-0f6a-4b9a-b729-7a79850563a5)

Although OpenSubtitles.com API docs is very well documented and easy to understand and play with, I can contribute by sharing python implantations from the Kodi addon, if it helps.

-----------------------------------------------------------------------------------------------------------------

Link:
https://github.com/kodi7rd/kodi7rd.github.io/blob/master/builds/build21_kodirdil/build21_kodirdil/addons/service.subtitles.All_Subs/resources/sources/opensubtitles.py

Keys to note:

1. For authorization - You'll see there that in addition of having the option as a user to configure his own OpenSubtitles API Key, by default it uses every call a random API Key from an [online list](https://kodi7rd.github.io/repository/other/DarkSubs_OpenSubtitles/darksubs_opensubtitles_api.json) - In order to give the addon users easy life without configuring anything, and to withstand the daily limit for each API key (Search - no limits, download - 100/day).

It is very stable for a long time. (I guess that for the Stremio addon it is probably better to let the user configure his own API Key, but just letting you know that the alternate option works well, with enough API keys created by designated accounts)

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/448f0fd4-0246-4e28-90a9-731eb0e1f8f3)

-----------------------------------------------------------------------------------------------------------------

2. OpenSubtitles results pages list - 
You'll see in the code (Line 163), that it queries the API multiple times in a for loop. That is because the addon also let users search subtitles for all available languages, and each page consists of 50 subtitles. I guess that part is not needed, assuming the search langauge is Hebrew only, and all results will always be in the first page.

Twilight

**Comment by Nitzantomer1998** [comment]
1. I've gone through the OpenSubtitles documentation, which is really impressive and straightforward. I've also created a few API keys for development (100 downloads per day, but with caching). I prefer to keep these keys private so I can easily monitor their usage and decide if I need to expand by obtaining more API keys from a different account.

2. I found that Hebrew subtitles on OpenSubtitles are often limited, sometimes offering as few as eight options. Therefore, looping over ages isn't relevant. I believe it's never relevant because it shows all the subtitles if I'm correct. The pages are only for the frontend that uses them.

3. I don't know much about the DarkSub add-on for Kodi, but I will look into it.

I haven't pushed the OpenSubtitles source yet because I'm looking for an elegant solution to handle the 100-request limit. Currently, I call to swap to the next key, but as I said, I'm searching for a more elegant method. I'm also working on the configuration so users can choose their sources.

**Comment by TwilightMercy** [comment]
> I've also created a few API keys for development (100 downloads per day, but with caching). I prefer to keep these keys private so I can easily monitor their usage and decide if I need to expand by obtaining more API keys from a different account.

Great! That's what I meant. Keep them private of course, they are not needed to be shared in public. (in Kodi they are public because the addon runs locally on Kodi client so it needs remote access to the API keys list.)

As you've probably saw, each OpenSubtitles account can create up to 3 API Keys. and "under development" key grants 100 downloads/day. 

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/e069f1dc-1dc9-4c4c-96f8-4c6ddc26a3f1)


I've created 11 accounts for the Kodi addon, so all of his users has total limits of 3300 downloads/day. 
It works very stable up until today. 

By the way, can you explain "100 downloads per day, but with caching"? (Caching part)


> 2. I found that Hebrew subtitles on OpenSubtitles are often limited, sometimes offering as few as eight options. Therefore, looping over ages isn't relevant. I believe it's never relevant because it shows all the subtitles if I'm correct. The pages are only for the frontend that uses them.

Here I assume it's not relevant because each page can have 50 subtitles, and if the addon searches only for Hebrew language - there will be no more than one page of results. 

In Kodi addon the user can search in ALL languages so that's why it loops through the pages, but not needed here. 



> 3. I don't know much about the DarkSub add-on for Kodi, but I will look into it.

Link


> I haven't pushed the OpenSubtitles source yet because I'm looking for an elegant solution to handle the 100-request limit. Currently, I call to swap to the next key, but as I said, I'm searching for a more elegant method. I'm also working on the configuration so users can choose their sources.

I suggest to create enough accounts + api keys for internal addon configuration (private), and use them, wether if by order or choose randomly each API call. (In opensubtitles.py - look for "" function)

**Comment by Nitzantomer1998** [comment]
> By the way, can you explain "100 downloads per day, but with caching"? What does the caching part mean?

Sure. Assume you are using the same API key and request a specific list of subtitles (download/subtitles list). Here's how it works:

1. OpenSubtitles first checks if the same request has occurred in the last 24 hours using the same API key. If it has, it doesn't count the request towards the 100 downloads per day limit and returns the result quickly because it is stored in the cache.
2. If the request wasn't in the cache, OpenSubtitles processes the request, updates the request count (if it's a download), and then returns the result.

You can verify this by timing the requests (in milliseconds). If you make the same request twice, you'll notice the second one is much faster. Additionally, you can check the log of remaining requests and see that it hasn't changed for cached requests.

However, it's important to note that the time it takes for the first request compared to Wizdom might not be apparent, but OpenSubtitles is almost four times slower. This is because OpenSubtitles returns a lot of unnecessary information in the request body, rather than just the subtitles list or download.

> Here, I assume it's not relevant because each page can have up to 50 subtitles, and if the addon searches only for Hebrew subtitles, there will be no more than one page of results.

Correct, I’m only retrieving subtitles from OpenSubtitles in Hebrew, so it’s always just one page. There's no need to loop through multiple pages, as you mentioned.

> Are you also using Kodi?

No, I used Kodi many years ago and found it lacking. Recently, I got back into watching old movies and TV series, so I searched for a program, and a friend recommended Stremio. I've been using it since.

> I suggest to create enough accounts + api keys for internal addon configuration (private), and use them, wether if by order or choose randomly each API call. (In [opensubtitles.py](https://github.com/kodi7rd/kodi7rd.github.io/blob/master/builds/build21_kodirdil/build21_kodirdil/addons/service.subtitles.All_Subs/resources/sources/opensubtitles.py) - look for "get_random_key" function)

Already been executed, thank you!

While you're here, could you open a new issue and include the URLs you used for Ktuvit? Their api documentation for Screwzira isn’t working.

**Comment by TwilightMercy** [comment]
> 1. OpenSubtitles first checks if the same request has occurred in the last 24 hours using the same API key. If it has, it doesn't count the request towards the 100 downloads per day limit and returns the result quickly because it is stored in the cache.

I see, thank you. 



> This is because OpenSubtitles returns a lot of unnecessary information in the request body, rather than just the subtitles list or download.

True, it includes extra information like rating / hearing impaired / etc.. (they are used in Kodi subtitles GUI)

But for Stremio I guess you only need language, file_name, and file_id for download. 



> No, I used Kodi many years ago and found it lacking. Recently, I got back into watching old movies and TV series, so I searched for a program, and a friend recommended Stremio. I've been using it since.


Today Kodi is very different and advanced compared to the past :)
Are you using Stremio + Torrentio with Real Debrid? Or free Torrentio version?


> Already been executed, thank you!

Great! If I may ask, you've created multiple accounts and API keys aswell?



> While you're here, could you open a new issue and include the URLs you used for Ktuvit? Their api documentation for Screwzira isn’t working.

Sure, this is most difficult website to implement, but important source. I will open soon detailed issue when I'll be on PC.

**Comment by Nitzantomer1998** [comment]
OpenSubtitles source has been implemented and added.

**Comment by TwilightMercy** [comment]
I've tested latest addon version with Wizdom + OpenSubtitles together - works great, accurate results through API search, for both movie and tv shows.

I don't know if it is needed, because TV shows imdb id works and find accurate episodes results, but reading:
https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/blob/main/src/services/osService.js#L8

According to [OpenSubtitles API docs](https://opensubtitles.stoplight.io/docs/opensubtitles-api/a172317bd5ccc-search-for-subtitles), they state that:
For movies - send imdb_id,
For TV shows - send the tv show imdb_id as parent_imdb_id, (in addition to season_number / episode_number)


![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/0f744f42-2b4e-41b1-ba20-93857fc971cf)


Maybe it will be more stable and accurate, but anyway anything works perfect from my testing.

**Comment by Nitzantomer1998** [comment]
Great job! I hadn't noticed this note.

I will look into it and perform some checks to verify its performance. If it proves to be even a bit more optimized, I will make the change soon.

**Comment by Nitzantomer1998** [comment]
Hi @TwilightMercy, as you mention this from the docs i did some experiments:

> According to [OpenSubtitles API docs](https://opensubtitles.stoplight.io/docs/opensubtitles-api/a172317bd5ccc-search-for-subtitles), they state that:
For movies - send Imdb ID as imdb_id
For TV shows - send the tv show Imdb ID as parent_imdb_id, (in addition to season_number / episode_number)

I checked how this would affect optimization, and honestly, it might be something for the future or perhaps something they deprecated. My comparisons show that the regular method (not using parent_imdb_id) performs better for both movies and series.

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/93198738/34a71e61-f536-4a64-8277-0094b851f9b4)

Just noting that we've already discussed the caching issue with OpenSubtitles. I replace the API key before each call, both for the optimized and regular methods.
